Name: api
Host: 0.0.0.0
Port: 8888

Log:
  ServiceName: api
  Level: info

Telemetry:
  Name: api
  Endpoint: http://jaeger:14268/api/traces
  Sampler: 1.0
  Batcher: jaeger

Redis:
  Host: redis:6379
  Pass: "123456"
  DB: 0

WebsocketRpc:
  Endpoints:
    - websocket-rpc-0:30000
    - websocket-rpc-1:30000
