version: '3'

services:
  jaeger:
    image: registry.cn-shanghai.aliyuncs.com/pathim/jaeger-all-in-one:latest-arm64
    restart: always
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - LOG_LEVEL=debug
    networks:
      im_lite:
        ipv4_address: 172.39.2.6

  elasticsearch:
    image: registry.cn-shanghai.aliyuncs.com/pathim/elasticsearch:7.13.4-arm64
    user: root
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
      - TZ=Asia/Shanghai
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      im_lite:
        ipv4_address: 172.39.2.7
  zookeeper:
    image: registry.cn-shanghai.aliyuncs.com/pathim/zookeeper:3.7-arm64
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    restart: always
    volumes:
      - ./data/zookeeper:/data
    ports:
      - "2181:2181"
    networks:
      im_lite:
        ipv4_address: 172.39.2.8
  #消息队列
  kafka:
    image: registry.cn-shanghai.aliyuncs.com/pathim/kafka:arm64v8-2.2.0
    ports:
      - 9092:9092
    environment:
      - KAFKA_LISTENERS=INTERNAL://:9093,CLIENT://:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,CLIENT://172.39.2.9:9092
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - TZ=Asia/Shanghai
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/kafka:/kafka
    networks:
      im_lite:
        ipv4_address: 172.39.2.9
    depends_on:
      - zookeeper
  kafka-ui:
    image: registry.cn-shanghai.aliyuncs.com/pathim/kafka-ui:latest-arm64
    ports:
      - 18080:8080
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=172.39.2.9:9092
      - KAFKA_CLUSTERS_0_NAME=docker
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    restart: always
    networks:
      im_lite:
        ipv4_address: 172.39.2.10
    depends_on:
      - kafka
      - zookeeper
  redis:
    image: registry.cn-shanghai.aliyuncs.com/pathim/redis:latest-arm64
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./data/redis:/data
    command: redis-server /etc/redis/redis.conf
    privileged: true
    networks:
      im_lite:
        ipv4_address: 172.39.2.11
  mongo:
    image: registry.cn-shanghai.aliyuncs.com/pathim/mongo:latest-arm64
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
    restart: always
    privileged: true
    networks:
      im_lite:
        ipv4_address: 172.39.2.12

# IM-Lite-Server
  websocket-rpc-0:
    image: registry.cn-shanghai.aliyuncs.com/pathim/websocket-rpc:latest
    restart: always
    ports:
      - "30000:30000"
      - "31000:31000"
    environment:
      - "POD_NAME=websocket-rpc-0"
      - "POD_IP=172.39.3.10"
    volumes:
      - ./websocket.yaml:/app/etc/websocket.yaml
    networks:
      im_lite:
        ipv4_address: 172.39.3.10
  websocket-rpc-1:
    image: registry.cn-shanghai.aliyuncs.com/pathim/websocket-rpc:latest
    restart: always
    ports:
      - "30001:30000"
      - "31001:31000"
    environment:
      - "POD_NAME=websocket-rpc-1"
      - "POD_IP=172.39.3.11"
    volumes:
      - ./websocket.yaml:/app/etc/websocket.yaml
    networks:
      im_lite:
        ipv4_address: 172.39.3.11
  api:
    image: registry.cn-shanghai.aliyuncs.com/pathim/api:latest-arm64
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./api.yaml:/app/etc/api.yaml
    networks:
      im_lite:
          ipv4_address: 172.39.4.10

networks:
  im_lite:
    driver: bridge
    ipam:
      config:
        - subnet: 172.39.0.0/16